# Generated by Django 4.0.6 on 2022-08-01 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Вес в кг.')),
                ('volume', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Объем в куб.м')),
                ('category', models.CharField(max_length=25, verbose_name='Категория груза')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('surname', models.CharField(max_length=70, verbose_name='Фамилия')),
                ('telephone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('passport', models.CharField(max_length=25, verbose_name='Номер пасспорта')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('telephone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('passport', models.CharField(max_length=25, verbose_name='Номер пасспорта')),
                ('driver_license', models.CharField(max_length=25, verbose_name='Номер прав')),
                ('cargo_category', models.CharField(max_length=25, verbose_name='Категория груза')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.cargo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25, verbose_name='Город')),
                ('country', models.CharField(max_length=25, verbose_name='Страна')),
                ('address', models.CharField(max_length=25, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=25, verbose_name='Гос номер')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=25, verbose_name='Грузоподъемность')),
                ('volume', models.DecimalField(decimal_places=3, max_digits=25, verbose_name='Объем')),
                ('brend', models.CharField(max_length=25, verbose_name='Марка')),
                ('model', models.CharField(max_length=25, verbose_name='Модель')),
                ('vin_code', models.CharField(max_length=25, verbose_name='VIN код')),
                ('cargo_categoty', models.CharField(max_length=25, verbose_name='Категория груза')),
            ],
        ),
        migrations.CreateModel(
            name='WayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.driver')),
                ('point_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.location')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.truck')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.invoice')),
                ('way_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.waybill')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='point_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.location'),
        ),
    ]
