# Generated by Django 4.0.6 on 2022-08-02 16:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, help_text='м', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Длина груза')),
                ('width', models.DecimalField(decimal_places=2, help_text='м', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ширина груза')),
                ('higth', models.DecimalField(decimal_places=2, help_text='м', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Высота груза')),
                ('weight', models.DecimalField(decimal_places=2, help_text='кг', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес')),
                ('volume', models.DecimalField(blank=True, decimal_places=3, help_text='куб.м', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запсис')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': ('Клиент',),
                'verbose_name_plural': ('Клиенты',),
                'ordering': ('-create_date',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запсис')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': ('Категория',),
                'verbose_name_plural': ('Категории',),
                'ordering': ('-create_date',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('surname', models.CharField(max_length=70, verbose_name='Фамилия')),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('passport', models.CharField(max_length=25, unique=True, verbose_name='Номер пасспорта')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запсис')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': ('Клиент',),
                'verbose_name_plural': ('Клиенты',),
                'ordering': ('-create_date',),
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('passport', models.CharField(max_length=25, unique=True, verbose_name='Номер пасспорта')),
                ('driver_license', models.CharField(max_length=25, unique=True, verbose_name='Номер прав')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запсис')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('cargo_category', models.ManyToManyField(max_length=25, related_name='driver_categories', to='cargo_app.category', verbose_name='Категория груза')),
            ],
            options={
                'verbose_name': ('Водитель',),
                'verbose_name_plural': ('Водители',),
                'ordering': ('-create_date',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запсис')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('cargo', models.ManyToManyField(related_name='my_cargos', to='cargo_app.cargo', verbose_name='Мои грузы')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargo_app.customer')),
            ],
            options={
                'verbose_name': ('Заявка',),
                'verbose_name_plural': ('Заявки',),
                'ordering': ('-create_date',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25, verbose_name='Город')),
                ('country', models.CharField(max_length=25, verbose_name='Страна')),
                ('address', models.CharField(max_length=25, verbose_name='Адрес')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запсис')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': ('Адрес',),
                'verbose_name_plural': ('Адреса',),
                'ordering': ('-create_date',),
                'unique_together': {('country', 'city', 'address')},
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=25, verbose_name='Гос номер')),
                ('weight', models.DecimalField(decimal_places=3, help_text='тонн', max_digits=25, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Грузоподъемность')),
                ('volume', models.DecimalField(decimal_places=3, help_text='куб.м.', max_digits=25, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем')),
                ('brend', models.CharField(max_length=25, verbose_name='Марка')),
                ('model', models.CharField(max_length=25, verbose_name='Модель')),
                ('vin_code', models.CharField(max_length=25, unique=True, verbose_name='VIN код')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запсис')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('cargo_category', models.ManyToManyField(max_length=25, related_name='truck_categories', to='cargo_app.category', verbose_name='Категория груза')),
            ],
            options={
                'verbose_name': ('Грузовик',),
                'verbose_name_plural': ('Грузовики',),
                'ordering': ('-create_date',),
            },
        ),
        migrations.CreateModel(
            name='WayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запсис')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('drivers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargo_app.driver')),
                ('point_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybill_loaction_a', to='cargo_app.location')),
                ('point_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybill_loaction_b', to='cargo_app.location')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargo_app.truck')),
            ],
            options={
                'verbose_name': ('Путивой лист',),
                'verbose_name_plural': ('Путевые листы',),
                'ordering': ('-create_date',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запсис')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('invoice', models.ManyToManyField(to='cargo_app.invoice')),
                ('way_bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.waybill')),
            ],
            options={
                'verbose_name': ('Заказ',),
                'verbose_name_plural': ('Заказы',),
                'ordering': ('-create_date',),
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='point_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_loaction_a', to='cargo_app.location'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='point_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_loaction_b', to='cargo_app.location'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='category',
            field=models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.PROTECT, to='cargo_app.category', verbose_name='Категория груза'),
        ),
    ]
