# Generated by Django 4.0.6 on 2022-08-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
