# Generated by Django 4.0.6 on 2022-08-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0002_customer_is_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ('-create_date',), 'verbose_name': 'Груз', 'verbose_name_plural': 'Грузы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-create_date',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('-create_date',), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
