# Generated by Django 4.0.6 on 2022-08-03 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0003_alter_cargo_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='point_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybill_loaction_a', to='cargo_app.location'),
        ),
    ]
